(ns closso.views.home
  (:require [closso.views.util :as util]
            [closso.session :as session]
            [reagent.core :as reagent :refer [atom]]
            [reagent-forms.core :refer [bind-fields]]
            [ajax.core :refer [POST]]))

(defn home []
  [:div
   [:h1 "Home Page"]
    [:p "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pulvinar purus in tincidunt feugiat. Quisque iaculis sed purus fermentum condimentum. Nulla facilisi. Nam laoreet placerat lacus non porttitor. Vivamus nec magna vel lacus feugiat tincidunt. Pellentesque egestas sollicitudin sem a fermentum. Suspendisse efficitur dolor at lobortis vehicula. Suspendisse a dictum erat. Aenean quam libero, iaculis et mi in, ultrices tincidunt tellus. Sed consectetur mi et velit viverra, eget dignissim purus eleifend."]
   [:p "Duis in lacus in diam eleifend volutpat. Proin tristique sapien eros, eget dignissim massa luctus at. Sed mattis nibh ipsum, maximus tristique augue ornare et. Maecenas porttitor sollicitudin ultricies. Mauris bibendum tortor ac orci ornare, nec pharetra magna ullamcorper. Aliquam porttitor ligula felis. Sed congue dapibus maximus. Integer id sollicitudin ex, non commodo justo. Proin consequat ante eget pellentesque mattis. Proin et molestie dui. Maecenas ut justo auctor, condimentum tortor id, eleifend dui. Etiam eu quam a tellus elementum iaculis ac eget tortor. Aenean tristique elementum purus. Proin rutrum, nibh ac pretium imperdiet, leo neque consectetur lectus, id consequat purus est non nisl. Nunc tincidunt vehicula eleifend."]
   [:p "Donec suscipit augue sed tincidunt convallis. Integer metus nibh, lobortis ac justo cursus, egestas eleifend urna. Praesent lacinia lobortis felis non sagittis. Morbi rhoncus sit amet sapien quis hendrerit. Fusce molestie nibh tortor, at rutrum urna consectetur eu. Donec volutpat ultrices velit vulputate convallis. Pellentesque elit nibh, accumsan sit amet neque et, lobortis iaculis arcu. Nunc risus ante, pharetra ac dui et, rhoncus sollicitudin arcu. Curabitur mattis risus mauris, non imperdiet erat consequat eget."]
   [:p "Praesent commodo odio quis elit convallis, eu porttitor massa fermentum. Pellentesque in faucibus purus. Nullam facilisis neque tortor, in mollis arcu efficitur et. Nulla facilisi. Vestibulum cursus enim leo, nec mattis justo porta quis. Ut et velit cursus, interdum purus vitae, viverra magna. Nam faucibus hendrerit elit. Aenean pharetra quam nec orci posuere, sed cursus nibh venenatis. Sed nisl ipsum, porta eu est eget, suscipit vehicula mi. Morbi finibus dolor ut purus efficitur venenatis. Vivamus malesuada, lacus eget dignissim accumsan, purus nunc feugiat nunc, ac posuere neque lorem at elit. Nulla facilisi. Sed felis magna, dictum at vehicula sed, feugiat sed sapien."]
   [:p "Aenean tincidunt leo at molestie ullamcorper. Duis in tincidunt massa. Suspendisse eu consectetur ipsum. Vestibulum eleifend tincidunt ultrices. Proin iaculis leo vitae sodales commodo. Mauris at arcu quam. Cras elementum arcu eget lacinia imperdiet. Nullam iaculis, libero eu aliquet convallis, eros felis facilisis tellus, vel commodo dui lorem id tellus. Fusce mollis ex diam, eleifend ornare dui posuere vitae. Etiam laoreet rutrum facilisis. Etiam aliquam, dui sed lacinia scelerisque, sapien mi maximus velit, ac luctus sapien diam et ipsum. Aliquam pellentesque consequat suscipit. Vivamus malesuada mi in nisi tempus, eget aliquet mi tempor. Donec scelerisque eros nec est aliquam maximus. Vestibulum posuere pharetra arcu, ac aliquet mauris."]
   [:p "In suscipit dictum tristique. Vivamus mattis maximus elit, lobortis finibus lectus tempor et. Nullam magna erat, dignissim nec vehicula vitae, aliquam id felis. Fusce eget nisl vehicula, porttitor lacus nec, volutpat mi. Fusce rutrum tellus massa, in venenatis sapien pretium vel. Pellentesque tincidunt sem est, vitae congue quam placerat in. Cras id tristique augue, vitae hendrerit quam. Curabitur vel vehicula nulla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras venenatis ex ac diam vestibulum tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id dolor venenatis nibh pellentesque pulvinar vel at enim. Suspendisse dapibus blandit felis, eget accumsan ante sodales vitae. In a elit sed diam sollicitudin vulputate eget consequat mauris. Aliquam efficitur nunc arcu, sit amet aliquet urna tincidunt sagittis."]
    [:p "Duis in lacus in diam eleifend volutpat. Proin tristique sapien eros, eget dignissim massa luctus at. Sed mattis nibh ipsum, maximus tristique augue ornare et. Maecenas porttitor sollicitudin ultricies. Mauris bibendum tortor ac orci ornare, nec pharetra magna ullamcorper. Aliquam porttitor ligula felis. Sed congue dapibus maximus. Integer id sollicitudin ex, non commodo justo. Proin consequat ante eget pellentesque mattis. Proin et molestie dui. Maecenas ut justo auctor, condimentum tortor id, eleifend dui. Etiam eu quam a tellus elementum iaculis ac eget tortor. Aenean tristique elementum purus. Proin rutrum, nibh ac pretium imperdiet, leo neque consectetur lectus, id consequat purus est non nisl. Nunc tincidunt vehicula eleifend."]
   [:p "Donec suscipit augue sed tincidunt convallis. Integer metus nibh, lobortis ac justo cursus, egestas eleifend urna. Praesent lacinia lobortis felis non sagittis. Morbi rhoncus sit amet sapien quis hendrerit. Fusce molestie nibh tortor, at rutrum urna consectetur eu. Donec volutpat ultrices velit vulputate convallis. Pellentesque elit nibh, accumsan sit amet neque et, lobortis iaculis arcu. Nunc risus ante, pharetra ac dui et, rhoncus sollicitudin arcu. Curabitur mattis risus mauris, non imperdiet erat consequat eget."]
   [:p "Praesent commodo odio quis elit convallis, eu porttitor massa fermentum. Pellentesque in faucibus purus. Nullam facilisis neque tortor, in mollis arcu efficitur et. Nulla facilisi. Vestibulum cursus enim leo, nec mattis justo porta quis. Ut et velit cursus, interdum purus vitae, viverra magna. Nam faucibus hendrerit elit. Aenean pharetra quam nec orci posuere, sed cursus nibh venenatis. Sed nisl ipsum, porta eu est eget, suscipit vehicula mi. Morbi finibus dolor ut purus efficitur venenatis. Vivamus malesuada, lacus eget dignissim accumsan, purus nunc feugiat nunc, ac posuere neque lorem at elit. Nulla facilisi. Sed felis magna, dictum at vehicula sed, feugiat sed sapien."]])
